### ISSUE TITLE
Login design issue, need advice

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#116]
Hi @rivantsov ,

May I have your advice on the following design issue for user login?
I would like to separate user into 2 category:
a. System user, which could have role of Support, Supervisor, Manager and SysAdmin
b. Customer
Since Customer naturally have more information required than system user, I would think it is logical to create 2 separate entity for them, ie, IUser and ICustomer, however, at the back both login details will be shared by using the Login module.

In order to use the Role base Authorization, I suppose in the EntityApp we need to override the GetUserClaims and adding the Role, as following from the BookStore sample:

` public override IList<Claim> GetUserClaims(OperationContext userContext) {
      var claims = base.GetUserClaims(userContext);
      var session = userContext.OpenSession();
      using (session.WithElevatedRead()) {
        var userId = userContext.User.UserId; 
        var user = session.GetEntity<IUser>(userId);
        Util.Check(user != null, "User not found, user id: {0}", userId);
        claims.AddRole(user.Type.ToString());
      }
      return claims; 
    }`

However, from the userContext.User we would not be able to differentiate the login is either from System User or Customer, so we may end up have to check for both tables every time, looks quite ugly to me.

Questions:
1. Can we have extra info to store into the login module, such as login type?
2. Do you think the above design is correct? Appreciate your comment to improve it.

Thank you very much.
Jason Law

**Comment by rivantsov** [comment]
The login module is supposed to hold logins (username/passwords), only and nothing else. UserTypes and the whole authorization model is part of your app, it is specific to your app, and putting any of this into login module would be out of place. Login module gives you UserId of logged-in user, and you do the rest starting from it. You load user record by Id, lookup user type/role(s), etc. 
In fact, it's all right there, in the example, GetUserClaims, I put this code there on purpose to demo how to add 'authorization' info after login. Login module sets UserId in OperationContext after successful login. Then the code in GetUserClaims looks up the user record in db (IUser is part of BookStore app, not Login module), and the code adds UserType role to claims. Lookup UserType enum, it is exactly like your system-User or customer roles, a bit more fine-grained.

**Comment by rivantsov** [comment]
as for db lookup 'every time' - no, the scenario there is to put these roles into Jwt token, that is submitted with every request, and then you can get it from token. 
If you want to keep it on server - then you have to hold server-side session. This appears to be out of fashion lately, so I deprecated this module (used to have it). Anyway, there are 'standard' solutions for server-side sessions, look it up - use these if you need to. 
Another alternative - data cache, so that user lookup is not expensive, when user is cached. Data caching in VITA is in the plans

**Comment by jasonlaw** [comment]
Thank you very much for the detail explanation.
May I know how to get the info data back from the token?

I am really looking forward the Data caching in VITA. Thank you very much for this great framework.

**Comment by rivantsov** [comment]
about getting data from token - looks like now that's not directly available. The code in JwttokenHandler extracts only UserName and UserId and AltUserId, and that's it. Something to think about in the future. For now - you can create your own token handler and register it instead of Vita's handler, and in it get/set the info you need. You extend the SetUserFromClaims method and save the information in OperationContext.Values dictionary; this OpContext is the one available to ApiControllers.

**Comment by jasonlaw** [comment]
Alright, looking forward the ability to get data from token in VITA.
Thank you very much!
