### ISSUE TITLE
Coming Next

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#129]
Hello Roman,
What are you working on with vita at this moment? What is comming next?
Do you have any list of work in progress and new things for Vita?
I am making lots of changes on my app because of the changes on version 3, and i canot go back because 80% of my users already updated to the latest version of my app.
So i am starting resolve some problems most of them because of performance issues. 
Thanks for your time.

**Comment by rivantsov** [comment]
Hi
thanks for asking.. what I'm working on.. pretty busy at my daytime-work-from-home job, I at MS Cloud security division now, and there's a lot happening there. But continuing with VITA. 

Right now building GraphQL integration. It seems like a bit outside of core ORM functionality, but after some careful analysis, I think GraphQL is the future, it is much better than REST, solves a lot of problems we had before. And providing support for it - it will shape a lot of things in the underlying ORM, and determines some key functionality there. So I thought it is important to have it, to know which things are needed inside core VITA. 
I expect to publish the first bits of GraphQL support in a couple of months. 

After that - back to core VITA, I was planning to first rewrite the LINQ engine, long overdue, bunch of spaghetti and patches. Badly needed upgrade, new dev is impossible with this mess. 

After that - the rest.. caching, authorization, etc. But... let's see if we can change priorities. 

About your perf problems. What kind of problems? Let's get more info.
1. Are you saying that you used data cache feature in v2, and now in v3 (no data cache), the perf is considerably down so you attribute it to lack of cache? 
2. If yes, we need to confirm it is the case, and that it cannot be something else missing. A lot of things changed in v3, it might not necessarily be the data cache only. And there might be something we can do even without cache. 
3. Low perf happens with updates, or with querying the data? Did you look at SQL logs and identify the points of slow perf?
4. Is it some complex queries that are slow? or just simply too many simple queries, reading many times the same  damn stuff? - in this latter case this CAN be fixed with data caching. But...
5.  Are you taking advantage of .Includes feature for queries? this might make things much faster, eliminate a lot of inefficiences
6. Finally, we can identify a list of tables that are queried very often, and build some quick simple lookup feature outside VITA core engine for now. 

So, let's work on this, we can fix it, no need to go back to old version, the v3 is sooo much better 

Roman

**Comment by rubenalves** [comment]
It's good to know that new things are coming.

I think that i have made some progresso on the performance of my app, on some cases i am loading more information tha is needed but it is resolving some performance problems, but for now i can live with it.

I asked for that was coming to plane new funcionality on my app, if you have any idea of how to make the cache work better i apreciate, the rest was just curiosity.

Thanks.

Ruben

**Comment by rivantsov** [comment]
all right then. 
in this case my advice for now - start looking at GraphQL, pretty sure your app architecture can benefit a lot from it.

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

Really looking forward for the GraphQL support in vita. :)
Hope there will be a BookStore example based on GraphQL as well.
Thank you very much!

**Comment by rubenalves** [comment]
Hello Roman

I am opening this thead again justo to know if you ave any news on Data Cache
I hade to move back to verion 1.9.3.1 because of this, it is working fine for me, but probably GraphQL only works with 3.x

Thanks.
