### ISSUE TITLE
Advice needed

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#138]
Hi,

I have the following entity model design, where ITrans (Inventory transactions) will supposedly manage the ISKU.Qty and ILOT.Qty. That means, only an entry in ITrans can update Qty in ISKU and ILOT.

    [Entity]
    [Validate(typeof(InventoryModule), nameof(InventoryModule.ValidateTrans))]
    public interface ITrans
    {
        [PrimaryKey, Auto(AutoType.NewGuid)]
        Guid Key { get; set; }

        [AutoTenantID]
        string TenantID { get; }

        [Size(2)]       
        string TransType { get; set; }

        [Size(nameof(SKU))]
        string SKU { get; set; }

        [Size(nameof(LOT))]
        string LOT { get; set; }

        int Qty { get; set; }
    }

    // Stock Keeping Unit 
    [Entity, PrimaryKey("TenantID, SKU") ]
    [Display("[{TenantID}] {SKU}")]
    public interface ISKU
    {
        [AutoTenantID]
        string TenantID { get; }

        [Size(nameof(SKU))]
        string SKU { get; set; }        

       string Description { get; set; }
              
        int Qty { get; set; }

        IList<ILOT> LOTs { get; }
    }

    [Entity, PrimaryKey("SKU, LOT")]
    [Display("{SKU} {LOT}")]
    public interface ILOT
    {
        [AutoTenantID]
        string TenantID { get; }

        [CascadeDelete]
        ISKU SKU { get; set; }

        [Size(nameof(LOT))]
        string LOT { get; set; }

        int Qty { get; set; }
    }

In that case, 
1. May I know how to make ISKU.Qty & ILOT.Qty readonly but allow to be updated by ITrans?
2. I plan to do the update Qty on ITrans SaveEvents.SavingChanges, do you think that is the right place?
3. How should I do the update? Retrieve back the SKU & LOT entity for updating, or directly update with SQL command?
4. Will there be any concern on concurrent write? What if the saving transaction include SKU or LOT entity? 

For e.g.
   var sku = session.GetEntity<ISKU>("A");
   sku.Description = "Update descrition";
   var itrans = session.NewTrans();
   itrans.SKU = "A";
   itrans.Qty = 10;
   session.SaveChanges();

In this eg, say we will update the SKU.Qty by retrieving the entity back for update, in this case, will either missing the Qty update or Description update?

Sorry for the long question, really appreciate your advice.

**Comment by rivantsov** [comment]
ok, my first question is - ITrans references ILot (and thru ILot references ISku), but why you do not have reference directly, like 'ILot Lot {get; set;}' in ITrans entity, instead of these 2 string properties?
if you have this ref, then you can reach directly to ILot and then to ISku
As for possible arrangement, ITrans is tied to ILot, so you can create extension method for new trans: 

public static ITrans NewTrans(this ILot lot, TransType transType, int qty) {
  var session = EntityHelper.GetSession(lot); 
  var trans = session.NewEntity<ITrans>();
  trans.Lot = lot;
  trans.TransType = transType;
  trans.Qty = qty;
  // update Lot and Sku
  lot.Qty += qty;
  lot.Sku += qty;
  return trans; 
} 

now you create trans like this: 
  var lot = session.GetEntity<ILot>(lotKey); 
  lot.NewTrans(TransType.SomeType, someQty); 
  session.SaveChanges(); 

As for protecting Qty in ILot and ISku, from modification - well, you can do this if define only {get;}, but then change the value using EntityHelper.SetProperty helper method (set by name), but ... is it really needed? 
In general, if you provide convenient method like NewTrans above that does it all, there's no incentive for a programmer (even if it is yourself), to mess up with these numbers directly, simpler to call this method; I usually use this kind of reasoning - provide convenient method for doing it right way, then don't worry about wrong way.

**Comment by rivantsov** [comment]
also, an alternative, a bit more heavy - to run update query to recalc totals of trans records for Lot and SKU, and update them, using LINQ-based updates. I have an example in TestLinqNonQuery_Update unit test method, orderTotalsQuery - it recalcs and updates order totals based on details recs

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

Thanks for your advice, I will revise the model design.

Btw, since my SKU entity has composite primary keys of TenantID and SKU, when I try to get the LOT from it with the following method, it will hit the error.

May I know what is the correct way for that? Thanks again.

Method:
   public static ILOT GetLOT(this ISKU sku, string lot)
        {
            var session = EntityHelper.GetSession(sku);
            return session.EntitySet<ILOT>().Where(x => x.SKU == sku && x.LOT == lot).FirstOrDefault();
        }


Error:


Vita.Data.Linq.Translation.LinqTranslationException: Linq to SQL translation failed, invalid expression: Equal operator for entities with composite key is not supported. Expression: x.SKU.
 ---> System.Exception: Equal operator for entities with composite key is not supported. Expression: x.SKU.
   at Vita.Entities.Util.Throw(String message, Object[] args)
   at Vita.Data.Linq.Translation.ExpressionTranslator.GetPrimaryKeyAccessor(Expression expression, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.CheckEqualOperator(BinaryExpression expression, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.AnalyzeEqualNonBoolOperator(BinaryExpression expression, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(Expression expression, IList`1 parameters, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.Analyze(Expression expression, TranslationContext context)
   at Vita.Data.Linq.Translation.ExpressionTranslator.<>c__DisplayClass51_0.<AnalyzeBinaryOperator>b__0(Expression op)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()

**Comment by rivantsov** [comment]
ah, you have compare PK fields, not entity objects: 
where(x => x.Sku.TenantId == sku.TenantId && x.Sku.OtherId == sku.OtherId && ..)

**Comment by rivantsov** [comment]
Regarding composite PK for SKU - I would strongly advise against composite keys, anywhere; except maybe simple link tables (like IBookAuthor).
 Composite PKs do not work well in LINQ translation, and also some important functionality like Includes is not available for these. And in general, they make things much messier in SQL and in c#. So my recommendation - use Guid column as PK in all tables, like ITRans, This will make things much much easier for the future, trust me

**Comment by jasonlaw** [comment]
OK clear now, will revise the model design based on your advice.
Thank you very much, really appreciate your help.
