### ISSUE TITLE
[Question] Opinion

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#139]
Hi @rivantsov ,

May I have your opinion on the following issue which I always find confusing:

1. Where should we put our business logic, Controller, Module or even in the entity extensions method?
2. Should we always validate the user input in both Controller and Module?

Thanks in advance.

**Comment by rivantsov** [comment]
well, about q1, good, and hard question; and as all hard questions it has no definite answer, yes or no. It is somewhere in between, for the most possible lower-pain-in-the-butt outcome.
On the one hand, it is usually assumed that it is good to have all logic in 'biz-logic' assemblies, the ones that are not involved with any UI (like AspNet). But, if you try to follow this rule, you will soon see that all your controller methods (REST endpoints) are redirects to biz logic methods; they only add UserId as parameter (that is retrieved from auth token or smth in asp.net), and then just call biz logic method with the same name. 
that's a real annoyance with REST, the need to create a separate handler method for every endpoint, and you gonna need a lot of endpoints for any real world app. And it's mostly boiler plate, boring redirect code.
 Another bad thing, even after you build all these endpoints, every little change in UI (extra value/field on the page/view) - requires going thru all this call stack and modifying all code in DTO , controller and then biz logic.
BTW, GraphQL is an attempt to do it better, without separate strongly-typed endpoints for every little thing. But, we are with REST still, so the pain and the question remains. 

So when I was doing RESTful stack, I ended up with balanced approach, depending on the method. Roughly, if it is GET some stuff, not much logic, just read a few entities, convert to DTO and combine - then do it right in the controller. If later you need to change something, it is much easier. T**he GET methods are the most prone to change because of frequent UI adjustments, they are tied to UI, so make it as easy as possible on server side - in controller.** 

For POSTs, if it is some update/insert, with some logic and validation, then redirect it to biz logic assembly method. These things change less often, that's more than just UI, it is real logic, so it makes sense to redirect it there. And will make it easier for reuse (in some tool/console app, background job etc.)
So the answer is - keep it flexible, use your judgement.  
For q2 - follows from q1, you MUST do it in bizlogic method for updates, in this case controller check is not needed at all. GET methods need only maybe 'access rights' check, and not always, so you can do it right there in controller.
Hope this helps.

**Comment by jasonlaw** [comment]
Thank you so much for the details reply, it really helps.
