### ISSUE TITLE
Any plans to support Multi-Tenant databases?

### ISSUE THREAD

**Issue by jfware** [rivantsov/vita#14]
One thing we would like to have built into an ORM is support for a Multi-Tenant database?

[Multi-Tenant Data Architecture](https://msdn.microsoft.com/en-us/library/aa479086.aspx)

We use the shared database, shared schema approach. Currently we use a forked version of a relatively obscure micro-ORM that we added basic Multi-Tenant support to so none of our database interactions has to be concerned with the fact that it is Multi-Tenant, it is handled for us automatically.

**Comment by rivantsov** [comment]
it is already supported; there's demo (as a unit test that should be run manually), here: 
https://github.com/rivantsov/vita/blob/master/5.UnitTests/Vita.UnitTests.Extended/MultiTenantTests.cs

the idea is the following: you can connect more than one database using App.ConnectTo(dbSettings); each DbSettings object should have a distinct DataSourceName. Then at run time, you set data source name in OperationContext, and then all data operations thru it will connect to corresponding data source (database). 
One important trick - if the Db schema/model is the same for all databases, then you should create a single DbModelConfig (one for all databases), and use it to create instances of DbSettings objects (each with its own conn string); this will avoid creating multiple instances of the same thing (DbModel object, quite big for complex databases, contains exact model of database)
Setting OperationContext.DataSourceName - you should do it at start of web request; possibly save it in UserSession at user login. You can hook to IWebCallNotificationService.WebCallStarting event, and set it in OperationContext.

**Comment by jfware** [comment]
Thanks for the quick response.

So it sounds like what you are saying is that there is support for the first of the three types (Separated DB) of Multi-Tenant databases in the above article. What I was asking about though is the third type, probably the most difficult to implement in an ORM and the reason we don't see it in them. Shared DB & Shared Schema. The TenantId is a column in every (shared) table and data for all tenants are stored in the same table. So basically we would need to tell the ORM what field is used as the TenantId for each table, perhaps using a new attribute on each table or something and then it would automatically handle the where clauses for us so none of our code has to be concerned with this storage detail.

Also, I cloned your repo and it doesn't build initially. The file 'VitaBooksSqlCe.sdf' is missing from both '505.Vita.UnitTests.Basic' and '510.Vita.UnitTests.Extended'.

**Comment by rivantsov** [comment]
About missing files - thanks, will add these, had been left out in move to github
Sorry I missed your note that you use multi-tenant with Shared DB, not separate db per tenant.  So support for shared db - the answer is yes and no. There are 2 kinds of SELECTs that Vita fires: 
1.  Standard queries using stored procs or pre-built SQLs - getentitybyId, getbykey, etc
2. LINQ queries using session.EntitySet<TEntity>()

First about (2) - you can easily implement support for automatic filters. OperationContext has QueryFilter property which is a dictionary of automatic filter expressions added to session.EntitySet<TEntity>() instances. 

   queryFilter.Add<IMyEntity, Guid>( (myEnt, tenantId) => myEnt.TenantId == tenantId);

This assumes that user session has a value under key 'tenantId' set. You should set it when user logs in: 

   opContext.UserSession.Values["tenantId"] = someID; 
The value will be preserved in user session between calls while user is still logged in.   
The OperationContext.QueryFilter property is assignable, so you can create a singleton QueryFilter with all filters for all entities that have Tenant ID column. You need to set it when web call starts and OperationContext is created. The easiest way to do this is to define base class for your controllers and override InitController method: 

  class MyBaseApiController : SlimApiController {
     override InitController(context) {
          base.InitController(context); 
          context.QueryFilter = GlobalQueryFilterSingleton; 
      } 
  }

With this arrangement all linq queries will have extra WHERE condition for tables that have TenantId column. 
Now about non-LINQ select calls (type 1). You can just avoid using them, so instead of 

   session.GetEntity<TEntity>(id); 

use LINQ query. 

  session.EntitySet<TEntity>().FirstOrDefault(e => e.Id == id);

It will be slightly less efficient, but not by much. The SelectByKey procs/SQLs will still be fired internally, when system lazy loads related child entities  in list properties (publisher.Books), but for these tenant ID will be satisfied automatically - as long as parent record (publisher) is with correct tenant. 
I think it will work for you, without much trouble. 
Let me know if you have any questions.

**Comment by rivantsov** [comment]
I wasn't quite clear in my post, regarding yes and no answer. Yes - meaning you can have it already by using QueryFilters and limiting to LINQ queries. No - in the sense of implementing multi-tenancy support for ALL operations, including group 1 (standard crud procedures) - that's feasible, in theory, but in practice would require a lot of extra machinery inside framework, which will stay there to be used very rarely. 
Returning to implementation with QueryFilters. One uncovered situation is Inserts, update and deletes. It would be nice to have TenantId columns to be assigned automatically on inserts, with extra filter on deletes; and never updated. I think this can be implemented by an attribute on the column. You can explore this path, just look at other entity attributes (like AutoAttribute) and see how it can be done. I will put it on my to-do list, but I am afraid it will take a while before I can get to it, too many urgent things to do right now. But I promise to provide any help I can if you try to explore this.
