### ISSUE TITLE
String field without nullable not allowed empty value

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#141]
Hi,

I have following entity:
~~~c#
  [Entity]
    [Display("{AuthID}({TenantID}) - {DisplayName}")]
    [UniqueClusteredIndex("AuthID, TenantID")]
    public interface IAuth
    {
        [PrimaryKey, Auto(AutoType.NewGuid)]
        Guid Key { get; }

        [Size(nameof(AuthID))]
        string AuthID { get; set; }

        [Size(nameof(TenantID))]
        string TenantID { get; set; }

        [Size(Sizes.Name)]
        string DisplayName { get; set; }
 }
~~~
When I save data with empty TenantID, it hit the following error:

~~~json
{
    "code": "ValueMissing",
    "message": "Value of TenantID may not be empty.",
    "tag": "TenantID",
    "path": "Auth/IAuth/8233e818-140f-4f6d-9779-09694a92eb28",
    "parameters": {}
  }
~~~

My expectation is a non-nullable string datatype should be allowed empty value. Is that not correct?

**Comment by rivantsov** [comment]
that is intentional, the fwk does not make distinction between null and empty value; the thinking is that if you make column/property as not empty, you want something meaningful to show up there, always. For other types, like int or double, you will have something like at least 0. But for strings, empty string is not meaningful, so I added additional restriction - no empty strings. It is in fact source of many confusions and mistakes in my experience, when non-null string columns contain empty strings, so I felt overall it is better to disallow it.

**Comment by rivantsov** [comment]
yes, it is generally not recommended to use nullable things in indexes; as far as I understand, you need this clustered index to cluster around AuthId and TenantId, so standard recommendation is to append PK (Key) to this index. Are you querying it a lot by AuthId and TEnantId? in any case, I would recommend staying with non-nullable column, and has some default value "DefaultTenant" or smth instead of empty string

**Comment by jasonlaw** [comment]
Thanks for the swift reply. I would try with a default value solution later. 

BTW, regarding the index, do you mean the clustered index should have included the pk (key), which makes it clustered (key, authid, tenantid)? May I know how is this different in action? Also, how would that make the uniqueness of authid+tenantid?

Thank you!

**Comment by rivantsov** [comment]
no, if you include PK, it should always be the last one, just to make index UNIQUE but primary ordering would be by something else (authId?). 
The whole point of specifying clustered index is that you want records on disk sit together based on some criteria - like for ex, by TenantId. A typical case is CustomerOrders table, you may set the clustered index (CustomerId, OrderId), with customerId being FK to Customer table; so all orders for customer will sit together, and as you typically, most often retrieve orders by customer, it will be less work for db server - it will go to one place on disk and get all or most of order records. But CustomerId is not unique for CustomerOrder table; you can either declare (CustomerId) clustered index - then MS SQL will append some unique value to each entry and make it unique internally - so that there's definite order of recs; or you can add explicitly OrderId - it is PK in the table, so resulting pair (CustomerId, OrderId) is unique. 
anyway, analyze how you query the table, and what order on disk would be most beneficial for you. It might be that there's no prefered order - that's fine, it used to be bad practice, but lately it is ok, table without clustered index is called Heap table - read some docs about all this

**Comment by jasonlaw** [comment]
Clear now, thanks!
