### ISSUE TITLE
[Question] SmartLoad functionality

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#179]
Hi @rivantsov ,

Am I right to say the new SmartLoad functionality is to cater for N+1 problems?
Does it totally replace the "Explicit Include"?
Is it only for GraphQL or in fact a total solutions for all cases?

Thanks!

**Comment by rivantsov** [comment]
> Am I right to say the new SmartLoad functionality is to cater for N+1 problems?

Yes

> Does it totally replace the "Explicit Include"?

Not quite yet, there might be some cases when you need explicit Include I think; the SmartLoad plans some more smart features, not only auto-include; but in the basic scenarios now - mostly yes, use SmartLoad, but always double check the SQL logs

> Is it only for GraphQL or in fact a total solutions for all cases?

Yes, the plan is for all cases, that's why it is part of VITA
