### ISSUE TITLE
News for Vita ORM

### ISSUE THREAD

**Issue by rubenalves** [rivantsov/vita#211]
Hello there, any upcomming releases planed for this year, any new features or any new on missing features thar where to come back from the old vertion?

No new is good news sometimes but it looks like the project is dead so this is to make it look a little mote alive :)

Thanks rivantsov for your greate work.

**Comment by rivantsov** [comment]
Hi
No worries, I'm still here, the project is going on. I know, long silence, sorry sorry. Fighting battles on different fronts, GraphQL, other issues at work. Many of subjects are connected indirectly to challenges we encounter in ORM. 

But work on VITA actually continues. Currently fixing on one troubled case, schema with many composite primary and foreign  keys, all over the place. Turned out Vita fails to figure out the links and fails on startup. Trying to replace the prior quite primitive algorithm with more robust one. This is a real world case that one the users encountered. Hope to wrap iit up soon. 

In addition to that there is a long to do list in Vita, so work goes on.  I hope to settle with other challenges and distracting issues pretty soon and focus much more on Vita. 
Other major release this year. Well, maybe, quite possible.  Stay tuned, I am still around, working

thank you for caring!

**Comment by rivantsov** [comment]
done, new version is pushed
