### ISSUE TITLE
Left outer join view on multiple columns

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#220]
Hi @rivantsov ,

May I know how to left outer join the following 2 tables into a view?

~~~C#
[Entity]
[PrimaryKey("Company, Monthly, Campaign")]
public interface ICompanySMSCampaign
{
    [CascadeDelete] ICompany Company { get; set; }
    DateTime Monthly { get; set; }
    [Size(100)] string Campaign { get; set; }
    int Qty { get; set; }
}

[Entity]
[PrimaryKey("Company, Monthly, Campaign, VoucherType")]
public interface ICompanyVoucherCampaign
{
    [CascadeDelete] ICompany Company { get; set; }
    DateTime Monthly { get; set; }
    [Size(100)] string Campaign { get; set; }
    VoucherType VoucherType { get; set; }
    int Qty { get; set; }
}

public interface ICompanySMSCampaignView
{
    ICompany Company { get; set; }
    DateTime Monthly { get; set; }
    string Campaign { get; set; }
    int SentQty { get; set; }
    int RedeemedQty { get; set; }
}
~~~

I have tried this but hit error:
~~~C#
 var smsSet = ViewHelper.EntitySet<ICompanySMSCampaign>();
        var voucherSet = ViewHelper.EntitySet<ICompanyVoucherCampaign>();

        var query = from s in smsSet
                    join v in voucherSet
                    on new { a = s.Company, b = s.Monthly, c = s.Campaign }
                    equals new { a = v.Company, b = v.Monthly, c = v.Campaign } into j
                    from lv in j.DefaultIfEmpty()
                    select new
                    {
                        s.Company,
                        s.Monthly,
                        s.Campaign,
                        SentQty = s.Qty,
                        RedeemedQty = lv == null ? 0 : lv.Qty
                    };
~~~

Error:

Exception thrown: 'System.Exception' in Vita.dll
An unhandled exception of type 'System.Exception' occurred in Vita.dll
Equal operator for entities with composite key is not supported. Expression: lv.

**Comment by jasonlaw** [comment]
Even if remove the left outer join part, I will still hit an runtime error with the following code.
~~~C#
 var smsSet = ViewHelper.EntitySet<ICompanySMSCampaign>();
        var voucherSet = ViewHelper.EntitySet<ICompanyVoucherCampaign>();

        var query = from s in smsSet
                    join v in voucherSet.Where(x => x.VoucherType == VoucherType.SMS)
                    on new { a = s.Company, b = s.Monthly, c = s.Campaign }
                    equals new { a = v.Company, b = v.Monthly, c = v.Campaign }// into j
                    //from lv in j.DefaultIfEmpty()
                    select new
                    {
                        s.Company,
                        s.Monthly,
                        s.Campaign,
                        SentQty = s.Qty,
                        RedeemedQty = v.Qty,
                    };
~~~

Error:
An unhandled exception of type 'Vita.Entities.DataAccessException' occurred in Vita.dll
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '* = *
     INNER JOIN "
vrewards_dev"."Company" c0$ ON c0$."Tenant_Id" = csm$."C' at line 5

Error Log File:
[ErrorLog.txt](https://github.com/rivantsov/vita/files/11723087/ErrorLog.txt)

**Comment by rivantsov** [comment]
well, let's look at it. 
First of all, the SQL in the error log file contains also references to Tenant_id columns in both tables, and also in the Company. So I guess tenant_id is part of Company's PK? - that's why it shows up in Join conditions. 
 Looks like you have multi-tenancy, with tenant_id in every table. That would be fine, unless you have composite PKs - there are some limitations with this, and looks like **you are hitting one of this limitations**. 

This limitation is partly because Linq engine in Vita still not perfect, but partly intentional since I mostly targeted to support mainstream 'simple PK' cases. Because complex exotic PK, with multiple columns and especially with large string field is really bad.   

I will explain. Good design rule for PK is to use single, simple (Guid or bigint), abstract column for PK.  Composite PK is really problematic. I use it ONLY for link tables in many-to-many relations - in this case two Guid columns. Because remember, PK is an INDEX used to lookup the rows, it is used extensively by the SQL engine, so it needs to be compact and have efficient lookup algorithm. What makes it worse, is that in MySQL (as in Oracle), your PK is automatically your clustered index (order of disk), there's no separate clustered index like in MS SQL or Postgres. And this makes things really bad, for maintaining the  PK and also referencing rows (relations) - you need to much more strict with choice of PK. Additionally composite PK brings complications in joins, and especially 'smart loading' becomes impossible, it uses IN operator which works only for single column PKs. 
That's why I always go for single Guid column for PKs. Your choice is quite bad, you include string(100) column into PK, this will result in really bloated index and will make SQL engine work much harder. 
What I suggest. You have 4 columns in PK in both tables - why not add a single Guid PK column, and leave the rest of the columns (companyId, campaign, etc) outside the PK? 

On another subject - why having 2 tables/entities at all for campaigns? Why not use single table, with column from both; make VoucherType nullable, if it is not null - it is Voucher campaign, it null - it is SMS campaign. Then you don't need the join at all! - it's all in a single row!
So my suggestion is to simplify the design, create separate Guid PK, and use a single table. 
By the way, Tenant_id does not need to be part of PK, not even in Company table (I assume company is a tenant?). You can have tenantId in other tables - but actually only in exceptional cases. Just don't include tenant in FKs or PK; but add index on it; this will make your life simpler

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

Thanks for the details clarification.

Simple PK vs Complex PK
In fact I did struggle about this when designing the table structure for the ICompanySMSCampaign entity. The reason I use composite PK here is because we will always query the data based on the company id, monthly and campaign. Hence I thought with composite PK the retrieval will have better performance. 
To be aligned with VITA, I will change it to simple PK, and making the company id, monthly and campaign Unique Index.

ICompanySMSCampaign & ICompanyVoucherCampaign 
These 2 entities are actually for the transaction log of sms campaign and voucher campaign (sorry the naming are bit confusing). I can combine these 2 into a single entity, but I thought clear separation is better for transaction tracking. 
Suppose I change these 2 entity with single pk strategy, but remain with 2 separated entity, I will still have a problem in joining both table since the matching key can't be the PK (auto id) but the companyid + monthly + campaign. 

Company as Tenant
This is a bit complex.
I have a base MultiTenant module project which will be used by multiple application.
The base Tenant entity have a Stub entity for the project extensions.

Base Tenant entities
~~~C#
[Entity]
public interface ITenant
{
    [PrimaryKey, AutoID] string Id { get; }
    [Size(30), Unique, DefaultValue("Id", true), NoUpdate] string Code { get; set; }
    [OneToOne] ITenantStub Stub { get; }
    [Utc, Auto(AutoType.CreatedOn)] DateTime CreatedOn { get; }
}

[Entity]
public interface ITenantStub
{
    [PrimaryKey, CascadeDelete, CascadeDeleteForward] ITenant Tenant { get; set; }
}
~~~

Project entity
~~~C#
public interface ICompany : ITenantStub
{
   // other properties
}

// replace the Company with the tenant stub
serv.ReplaceEntity(typeof(ITenantStub), typeof(ICompany));
~~~

Other entity in project which belongs to a company
~~~C#
public interface ICompanyCredit
{
    [PrimaryKey, AutoID] string Id { get; }
    [CascadeDelete] ICompany Company { get; set; }
    int Credit { get; set; }
    CreditTransType TransType { get; set; }
    [Size(300), Nullable] string RefId { get; set; }
    [Size(1000), Nullable, NoUpdate] string RefUrl { get; set; }
    [Size(255), Auto(AutoType.CreatedBy)] string CreatedBy { get; }
    [Utc, Auto(AutoType.CreatedOn)] DateTime CreatedOn { get; }
}
~~~

> Just don't include tenant in FKs or PK; but add index on it; this will make your life simpler
I am not quite understand this. How do we segregate for the multi-tenant data if we don't include it as at least the FK?

Thanks again.

**Comment by rivantsov** [comment]
Hi, sorry for the delay, had to think about it a bit. 
First about your last question: How do we segregate for the multi-tenant data if we don't include it as at least the FK?
I assume that all tables have unique 'id' as pk, value unique across all tenants, so simple FK ref to this single-value PK is enough to identify target record. That would happen automatically if you use identity column as PK on tables. You still can have TenantId in both tables, but do not need this in FK. Again, PK should be as compact as possbile, as well as ClusteredIndex, which for MySql is PK, so make it small! 
this also applies to your ICompanyCredit table - do not use string PK! Strings are expensive to store and especially compare!!

About your 2 campaign tables -  don't get it; if it is 'trans log' for 2 different things, why you need to join two trans log records? if two joined records from two different tables are about the 'same' thing (campaign), then why they are not just in one table that already represents the join?

Having separate module for Tenancy - looks ok, but I wonder how much actual functionality you share in this module; sometimes it's easier to just copy stuff to another project (the company/tenant table and a few fields); just not sure how much you gain with this 'sophistication'. Modules in Vita are supposed to have substantial amount of functionality, like Login module.

**Comment by jasonlaw** [comment]
Hi @rivantsov ,

Thanks again for the detail clarification, really appreciate it.

Sorry again to clarify a bit on the FK question.

> I assume that all tables have unique 'id' as pk, value unique across all tenants, so simple FK ref to this single-value PK is enough to identify target record.

All my tables  do have unique 'id' as pk, and value unique across all tenants.

> You still can have TenantId in both tables, but do not need this in FK. 

Do you mean the following?
~~~C#
[Entity]
public interface ITenant
{
  [PrimaryKey, Auto(AutoType.NewGuid)] Guid Id { get; } 
}

[Entity]
public interface ITenantData
{
  [PrimaryKey, Auto(AutoType.NewGuid)] Guid Id { get; }   
  ITenant Tenant { get; set; } // You still can have TenantId in both tables, but do not need this in FK. 
}

[Entity]
public interface ITenantDataDetails
{
  [PrimaryKey, Auto(AutoType.NewGuid)] Guid Id { get; }   
  ITenantData TenantData { get; set; } // so simple FK ref to this single-value PK is enough to identify target record.    
  ITenant Tenant { get; set; } // You still can have TenantId in both tables, but do not need this in FK. 
}
~~~
However, when we declare ITenant in the entity, VITA will automatically create the FK constraint in the table right?

In fact, this is also another question that I would like to check with you, can have this relationship within Entity but do not create the actual FK constraint in table? The reason is in some cases we still want to keep the data even those the reference entity is removed.

We have combined the 2 campaign tables, thanks for the advice.

About the Tenancy module, it is a bit complex, in fact, the tenant entity is part of the authentication module, which is similar to the LoginModule. Anyway, we fully agree with you that shouldn't complicated the design.

Thanks again for the reply, and this amazing framework. :)

**Comment by rivantsov** [comment]
> when we declare ITenant in the entity, VITA will automatically create the FK constraint in the table right?
yes

> ... but do not create the actual FK constraint in table? 

unfortunately no such option now. please create work item (issue) for this, so I wont forget; it is a valid point

**Comment by rivantsov** [comment]
and your code with Data/DataDetails - looks right, that's exactly what I meant
