### ISSUE TITLE
Save changes in batch mode hanges

### ISSUE THREAD

**Issue by suchym** [rivantsov/vita#34]
Hi Roman,

I am trying to store really huge object in the database.

At the beginning, it seems that everything works properly. 

I can see in Sql Server profiler executing batches, but suddenly somewhere at the end of execution all stops. Program hangs, Task Manager shows that CPU utilisation is about 20 % for saving process. The mouse sometimes stops responding...

I am waited about half of hour without any result.

When I tried to pause code execution I got into SaveChangesInBatchMode procedure ,
concrete this for loop:

foreach (var rec in updateSet.AllRecords) {
        rec.CustomTag = null; //clear temp ref that batch process has set
        rec.SubmitCount++;
        rec.EntityInfo.SaveEvents.OnSubmittedChanges(rec);
      }
I do not know what this loop do and why it is so slow. Maybe the event handler SubmittedChanges can do this.

Maybe, some statistics from debugger can help you to estimate the size of the data.:
updateSet.AllRecords.Count=1774815
updateSet.BatchCommands.Count=1512
updateSet.EntityInfos.Count=26
UseTrensactions=True
UseOutPrams=True

From my point of view this operation takes longer than submiting changes to database. 

I believe everything is executing in memory so there should be no such slowdown. That's just my guess.

Please, could you like to look at this problem and advise me how to solve it? Unfortunately, our objects are large and can not be divided into smaller parts. 

Best Regards

Milos

**Comment by suchym** [comment]
Addendum:
Here is propably the source of issue:

var childRecs = recs.Where(r => r.EntityInfo == refMember.Entity);

Performing Where on List<EntityRecord> for each IncomingReferences when list contains about 1700000 items is huge CPU load and slow...

void EntityEvent_IdentityEntitySubmitted(EntityRecord record, EventArgs args) {
      if (record.Status != EntityStatus.New) return;
      var recs = record.Session.RecordsChanged;
      foreach (var refMember in record.EntityInfo.IncomingReferences) {
        var childRecs = recs.Where(r => r.EntityInfo == refMember.Entity);
        foreach (var childRec in childRecs) {
          var refBackValue = childRec.ValuesTransient[refMember.ValueIndex];
          if (refBackValue == record)
            refMember.SetValueRef(childRec, refMember, record.EntityInstance); //this will copy foreign key
        }//foreach childRec
      }
    }

**Comment by suchym** [comment]
Sorry, wrong button click. I do not want to close this issue

**Comment by rivantsov** [comment]
oh man... I told you so, I told you so - remember our discussion of identities being thing of the past, and my strong advice to switch to guids before it's too late. Now we start to see the consequences, and I am afraid it's only the beginning. But 1.6 million records with identities over 26 tables in one transaction - that's really 'crazy' case. When I wrote this code you show that propagates the identity values across the batch, never ever have I thought about such case - a million records. What I had in mind is at most hundreds of records in one transaction. 
Whatever, let's see how to fix this. The problem is clear - terribly inefficient loop for propagating identities for large batches. But before we go to fix it, it would be really interesting to know, why it 'hangs' forever. Does it? or code continues to iterate, just takes a long time? 
As for the fix. 
I am currently all busy with .NET core version. I am working on a big refactoring of a code base, more than just switching dependencies. While doing this refactoring, I see the need for intermediate version based on old 4.6 fwk, to prepar users like you for refactored new .NET core version. Plus there are some small outstanding issues. So I think it's time to make this intermediate update - I plan to do it within a few days, and fix for your problem will be there. That's all I can offer. 
At the same time, while it is impressive (even for myself) that VITA can handle such a big load (except for identities),  I seriously think it's not a good approach to push such a big transaction - million+ records. 
That's not good from several points of views. I think you should seriously consider splitting it into several parts, with no more that few thousand records in one transaction

**Comment by rivantsov** [comment]
by the way, it would be interesting (and actually important!) to know if it just long loop, or actually something else. You said you waited for half-hour with no progress. I suspect it might be possible that SQL server runs out of smth - 1.6m records in transaction means huuuuge transaction log and extreme demand for other resources (memory, IO system, etc) that can bring it down to a halt. I know things happen if you runout of available log file space.
 This is a client machine importing data from server, right? so it is MS SQL dev edition? - this might have quite narrow restriction on sizes of resources. So please look more to know for sure - we might end up in situation (after I fix the identity propagation) when the process still crashes or hangs..

**Comment by suchym** [comment]
I have  done more additional tests to find out that extended save time is not caused by Sql Server.
It seems that problem is in loop as I described.
Sql Server did his work as I could see in profiler. Batches went to the end. Their execution stopped.  VITA started performing this loop:
foreach (var rec in updateSet.AllRecords) {
        rec.CustomTag = null; //clear temp ref that batch process has set
        rec.SubmitCount++;
        rec.EntityInfo.SaveEvents.OnSubmittedChanges(rec);
      }

The loop once finishes. The time , proportionally, depends on "updateSet.AllRecords" count.

**Comment by rivantsov** [comment]
thanks. But... what you've seen is that the first batch out of 1600 or so completed, and the app hang in this loop. We can't be sure SQL server will be able to swallow the whole thing. What I suggest is that you start looking into breaking it into multiple transactions/batches in code. 
And I am currently fixing this problem on my side

**Comment by rivantsov** [comment]
ah, wait, I misunderstood, sorry. Batches finished?! great! so it's only this last loop. I am fixing it then

**Comment by rivantsov** [comment]
should be fixed now

**Comment by suchym** [comment]
Awesome! I repeated the save of record that started everything. What previously took hours now takes minutes. Great work. Thank you very much.

**Comment by rivantsov** [comment]
great! everything appears to be working now. Closing the issue
