### ISSUE TITLE
v 1.9.3.1 pushed (source and nuget packages)

### ISSUE THREAD

**Issue by rivantsov** [rivantsov/vita#35]
details will follow shortly

**Comment by rivantsov** [comment]
details: 
https://github.com/rivantsov/vita/wiki/Code-changes-history

**Comment by gfreeman1** [comment]
When trying to update Vita.Data.SQLite to either 1.9.3.0 or 1.9.3.1, coming from 1.9.2.0, nuget wants to pull in EntityFramework, System.Data.SQLite.EF6 and System.Data.SQLite.Linq. This appears to be caused by the addition of System.Data.SQLite as a dependency in the Vita.Data.SQLite.nuspec file. The only note I could see related to the nuget packages was in the 1.9.3.0 changelog:

> Fixed nuget dependencies (versions) in drivers packages

Was this intentional?

As a temporary workaround, I manually removed the packages using Uninstall-Package with the -Force switch. Everything appears to be working fine after removing the packages and rebuilding / testing my app.

**Comment by rivantsov** [comment]
thanks for reporting this, I will fix that

**Comment by rivantsov** [comment]
you are right, this is a mistake, it should reference System.Data.SQlite.Core package. Quite confusing, DLL we need is System.Data.Sqlite.dll, but it is in xx.Core package. Will fix that.

**Comment by gfreeman1** [comment]
I figured it was a simple typo - easy to do with there being so many different System.Data.SQLite packages.

PS: Keep up the awesome work on VITA - I love how simple it makes data access compared to the alternatives!

**Comment by rivantsov** [comment]
thank you!
