### ISSUE TITLE
Login module

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#53]
I am not really clear how to use the Login module in my Mobile app, even after going through the unit test sample, could you please guide me where should I start (pointing me what to read, from code or any article/document, or any more examples would be great).

I have also some questions to clarify;
1. Can we run the Login module without UserSession?
2. How is the Login module work with OAuth?
3. Will there a plan to include OAuth 2.0 in the framework? How about OpenID Connect?

Thank you.

**Comment by rivantsov** [comment]
Here are the answers:
1. Login module without UserSession. There are basically 2 ways to 'remember' who's the user after he/she logins: 
   a. Use server-side session object, saved in some db, and return sessionId (token) to client/user device after login. This token is sent to server with every request in Http Header. This is UserSession module - in old 1.9 version, not migrated yet
  b. After login, server encrypts UserId, UserName (claims) into a token that is returned to the client. This is 'claim-based' authorization supported in ASP.NET. This claims token is sent back to server with each request. Server does not need Session in db - it decrypts UserId from this token. 
I would recommend exploring option b) first, look at ASp.NET core 'claims' packages - this seems to be preferred/trend these days. You can also take UserSession module from old version (as source code) and look at it, and maybe port it as source code.

**Comment by rivantsov** [comment]
Continuing. 
2. Login module and OAuth are alternative solutions. YOu can use one of them, OR you can use BOTH. The end result of both approaches - it returns UserId/UserName of returning user, that was previously registered with the system. 
3. VITA 1.9.3 (pre-core) version supported Auth2.0 and OpenId, there's a module and Sample app there, it is just not migrated yet - because it involves Web-related stuff which needs to be migrated first. You can look at old version, and take it as-is - all old code should work almost as-is. It will be migrated in the near future

**Comment by jasonlaw** [comment]
Thanks for the clear clarification!
I would wait for the UserSession module to be migrated, and hopefully there will be "claim-based" supported in the next release.
