### ISSUE TITLE
c#8.0 default interface implement

### ISSUE THREAD

**Issue by tylike** [rivantsov/vita#89]
hi,
There's the interface's default implementation in c#8.0, so you don't need the emitter generation interface to implement it?

**Comment by rivantsov** [comment]
I this is for completely different case. The default impl is provided by intf author (!) when he extends the existing (old)interface. In our case you (app dev) create interface. Me (and VITA) provides impl of the properties you defined. So with default intf impl supposedly you, intf author, will be providing implementation? just think about this, how it might apply to this situation? who is writing what?

**Comment by tylike** [comment]
Sorry, it's too simplistic for my description.
I use the devexpress xaf framework(www.devexpress.com), and I like xaf's domain component technology very much. It also uses interfaces to describe entities.
I think the biggest benefit of using interfaces is to write less code and implement multiple inheritance.
In xaf.dc, there is a domain logic concept that reuses business logic.

https://docs.devexpress.com/eXpressAppFramework/113262/concepts/business-model-design/business-model-design-with-xpo/domain-components/domain-components-basics?v=18.2

https://docs.devexpress.com/eXpressAppFramework/113364/concepts/business-model-design/business-model-design-with-xpo/domain-components/domain-logic?v=18.2

In developing a large project, it is easier to combine business logic.
However, now xaf.dc is a maintenance mode, I guess it's because c#8.0 supports the default default.

Of course, the interface still needs to be implemented, but it can be much simpler than it used to be (VITA or xaf).

Some of the differences are that VITA doesn't have logic class, and I think it's necessary to implement that business logic in the controller.
I think it might be better to have a logic class scheme. 
Thank you!

**Comment by rivantsov** [comment]
I looked at the links briefly, and still think this does not apply/help here. It is in the maintenance mode, but I don't think it's because of c# 8. I think in general the purpose of this is to follow general OOP pattern - data and code manipulating it encapsulated in a class; so an Entity has data props matching db columns AND code manipulating it, so this feature in devexpress was to help you build such components. 
But... I think this OOP pattern does not work well in data apps. While it works well in UI controls (that's where it actually started), following it with db-mapped entities results in a mess. You typically have 5-10 tables involved in some feature/piece, and same count of matching entities/classes. Which one should hold the business logic? you can try to put it in some root chosen one, or try to spread it between entities; but in my experiences it does not work well (I've seen big systems built like this, very big systems) - lots of cases with 'misplaced' code, like oh it should be here, not there, but then how we reach this other data etc. I came to conclusion that its better to leave data classes/entities alone, holding only data, and put logic into separate 'service' classes. 
So I think devexpress's deprecation of this feature indicates they came to the same thinking - it does not work well, to mix entities and logic. The biggest trouble here is entities are structured following tables which follow normalization rules - which is not how business logic wants its data, and not how logic code itself should be split/structured

**Comment by rivantsov** [comment]
and then the result is - VITA takes care of entities (interfaces defined by you, class IL emitted by VITA), and you have full freedom of creating logic classes/services/controllers. My initial recommendation is to put it into EntityModule (which hosts entities), and expose functionality as services registered in internal service dictionary. I do not provide any more facilities (base classes or whatever) for constructing logic, simply because I don't see how I can substantially assist in this
