### ISSUE TITLE
UTC tag for DateTime

### ISSUE THREAD

**Issue by jasonlaw** [rivantsov/vita#97]
Hi @rivantsov ,

May I know how exactly the UTC tag function?
Suppose my server and client has different timezone, should I always tag the UTC for all my datetime column?
For client it always pass to server with local time, in server do I need to convert it to UTC explicitly before save?
Can you point me any document for reference?

Thanks in advance.

**Comment by rivantsov** [comment]
The main use for UTC attribute is for system-assigned, auto fields, to let system know you want Utc value there, like CreateDateTime column on records. These columns, and MOST other datetime columns should always be UTC. You CAN use this attr on your own columns (that you assign with specific values), but you should be careful. The attr will convert to UTC (shift with time diff) if you accidentally assign DateTime value with Kind = Local - so in general, try to avoid this completely. 
In general, server local time is irrelevant in context of web or service app. All cloud servers (AWS or Azure) are on UTC. You should always use DateTime.UtcNow in your code (server side at least), business logic. The other benefit is when you test it locally, it runs the same as on cloud server. Assume your server code is always UTC, use DateTime.UtcNow everywhere, and never rely on DateTime.Kind. 
Without Utc attr, VITA will treat values as-is, no conversions. In db, datetime column does not have Kind property, so it stores UTC value and Vita reads it as UTC (entity prop returns UTC).
I talked to a guy from Windows Kerneal team once, and he admitted, that DateTime.Kind was a huge mistake in their design; originally it was thought it would help in desktop apps, with automatic handling of local vs UTC values, but it created more troubles than benefits. Since then, we all moved to mostly web apps, and this Kind stuff became really useless. So everything on the server should be UTC. 
Now, the case when you handle client's time, like time of appointment in user's calendar. This would require some careful consideration/design on your part. When user selects time in UI, it is 'local' time. It is sent as string in json - without Kind I guess. Server-side logic might treat it as-is, as local but local not for server local, but remote user local. But dateTime.Kind value should be UTC anyway - you should read it from json this way (Undefined at least), because Kind=local in time conversion functions would treat is a server-local, which can mess up everything. So your code can just save it as-is in db. If user selects 3pm his time, you save 15:00:00 in db. And then read/display it back like this. 
The problem comes when you need server code that scans the table and tries to find upcoming appointments (in the next 30 minutes or so), to send reminders or alerts. If you have users in different timezones, you have a problem. 
So the alternative is to save appointment time in UTC so it can be scanned in one common process. Then you need to have conversion routine - when user submits selected time (in his local time in UI), the server should convert it to UTC using client's timezone. We did this in the past: when user logs in, the browser's JavaScript code was sending timezone code to server (along with username and password); server saves timezone in user session (or can encode it in auth token), and then uses it in all time conversions like described above. 
Hope this helps

**Comment by rivantsov** [comment]
PS alternative to keeping timezone in session - send appt time as time+timzoneShift (DateTimeOffset in .NET, look it up, there's also standard format for this)

**Comment by jasonlaw** [comment]
Thank you so much for the detail clarification, really appreciate it.
